/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_LWRTB_WRAP_H_
#define SWIG_LWRTB_WRAP_H_

class SwigDirector_DeliveryCb : public lwrtb::DeliveryCb, public Swig::Director {

public:
    SwigDirector_DeliveryCb(zval *self);
    virtual ~SwigDirector_DeliveryCb();
    virtual void call(lwrtb::Bidder &arg0, lwrtb::DeliveryEvent const &arg1);
};
class SwigDirector_BidRequestCb : public lwrtb::BidRequestCb, public Swig::Director {

public:
    SwigDirector_BidRequestCb(zval *self);
    virtual ~SwigDirector_BidRequestCb();
    virtual void call(lwrtb::Bidder &arg0, lwrtb::BidRequestEvent const &arg1);
};
class SwigDirector_BidResultCb : public lwrtb::BidResultCb, public Swig::Director {

public:
    SwigDirector_BidResultCb(zval *self);
    virtual ~SwigDirector_BidResultCb();
    virtual void call(lwrtb::Bidder &arg0, lwrtb::BidResultEvent const &arg1);
};
class SwigDirector_ErrorCb : public lwrtb::ErrorCb, public Swig::Director {

public:
    SwigDirector_ErrorCb(zval *self);
    virtual ~SwigDirector_ErrorCb();
    virtual void call(lwrtb::Bidder &arg0, lwrtb::ErrorEvent const &arg1);
};

#endif
