/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_LWRTB_H
#define PHP_LWRTB_H

extern zend_module_entry lwrtb_module_entry;
#define phpext_lwrtb_ptr &lwrtb_module_entry

#ifdef PHP_WIN32
# define PHP_LWRTB_API __declspec(dllexport)
#else
# define PHP_LWRTB_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(lwrtb);
PHP_MSHUTDOWN_FUNCTION(lwrtb);
PHP_RINIT_FUNCTION(lwrtb);
PHP_RSHUTDOWN_FUNCTION(lwrtb);
PHP_MINFO_FUNCTION(lwrtb);

ZEND_NAMED_FUNCTION(_wrap_BidStatusToString);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_event_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_event_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_timestamp_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_timestamp_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_auctionId_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_auctionId_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_spotId_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_spotId_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_spotIndex_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_spotIndex_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_bidRequest_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_bidRequest_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_augmentations_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_augmentations_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_bid_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_bid_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_win_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_win_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_campaignEvents_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_campaignEvents_get);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_visits_set);
ZEND_NAMED_FUNCTION(_wrap_DeliveryEvent_visits_get);
ZEND_NAMED_FUNCTION(_wrap_new_DeliveryEvent);
ZEND_NAMED_FUNCTION(_wrap_new_DeliveryCb);
ZEND_NAMED_FUNCTION(_wrap_DeliveryCb_call);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_timestamp_set);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_timestamp_get);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_id_set);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_id_get);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_bidRequest_set);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_bidRequest_get);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_bids_set);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_bids_get);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_timeLeftMs_set);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_timeLeftMs_get);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_augmentations_set);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_augmentations_get);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_winCostModel_set);
ZEND_NAMED_FUNCTION(_wrap_BidRequestEvent_winCostModel_get);
ZEND_NAMED_FUNCTION(_wrap_new_BidRequestEvent);
ZEND_NAMED_FUNCTION(_wrap_new_BidRequestCb);
ZEND_NAMED_FUNCTION(_wrap_BidRequestCb_call);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_result_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_result_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_timestamp_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_timestamp_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_auctionId_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_auctionId_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_spotNum_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_spotNum_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_secondPrice_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_secondPrice_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_bidRequest_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_bidRequest_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_ourBid_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_ourBid_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_metadata_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_metadata_get);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_augmentations_set);
ZEND_NAMED_FUNCTION(_wrap_BidResultEvent_augmentations_get);
ZEND_NAMED_FUNCTION(_wrap_new_BidResultEvent);
ZEND_NAMED_FUNCTION(_wrap_new_BidResultCb);
ZEND_NAMED_FUNCTION(_wrap_BidResultCb_call);
ZEND_NAMED_FUNCTION(_wrap_ErrorEvent_timestamp_set);
ZEND_NAMED_FUNCTION(_wrap_ErrorEvent_timestamp_get);
ZEND_NAMED_FUNCTION(_wrap_ErrorEvent_description_set);
ZEND_NAMED_FUNCTION(_wrap_ErrorEvent_description_get);
ZEND_NAMED_FUNCTION(_wrap_ErrorEvent_originalError_set);
ZEND_NAMED_FUNCTION(_wrap_ErrorEvent_originalError_get);
ZEND_NAMED_FUNCTION(_wrap_new_ErrorEvent);
ZEND_NAMED_FUNCTION(_wrap_new_ErrorCb);
ZEND_NAMED_FUNCTION(_wrap_ErrorCb_call);
ZEND_NAMED_FUNCTION(_wrap_new_Bidder);
ZEND_NAMED_FUNCTION(_wrap_Bidder_init);
ZEND_NAMED_FUNCTION(_wrap_Bidder_start);
ZEND_NAMED_FUNCTION(_wrap_Bidder_shutdown);
ZEND_NAMED_FUNCTION(_wrap_Bidder_doConfig);
ZEND_NAMED_FUNCTION(_wrap_Bidder_doBid);
ZEND_NAMED_FUNCTION(_wrap_Bidder_bid_request_cb__set);
ZEND_NAMED_FUNCTION(_wrap_Bidder_bid_request_cb__get);
ZEND_NAMED_FUNCTION(_wrap_Bidder_bid_result_cb__set);
ZEND_NAMED_FUNCTION(_wrap_Bidder_bid_result_cb__get);
ZEND_NAMED_FUNCTION(_wrap_Bidder_delivery_event_cb__set);
ZEND_NAMED_FUNCTION(_wrap_Bidder_delivery_event_cb__get);
ZEND_NAMED_FUNCTION(_wrap_Bidder_error_cb__set);
ZEND_NAMED_FUNCTION(_wrap_Bidder_error_cb__get);
ZEND_NAMED_FUNCTION(_wrap_Bidder_setBidRequestCb);
ZEND_NAMED_FUNCTION(_wrap_Bidder_setDeliveryCb);
ZEND_NAMED_FUNCTION(_wrap_Bidder_setBidResultCb);
ZEND_NAMED_FUNCTION(_wrap_Bidder_setErrorCb);
#endif /* PHP_LWRTB_H */
